import sys

EPG_URL = "https://sulthanpamenan.github.io/padang-tv-playlist/epg.xml"
LOGO_URL = "https://padangtv.id/wp-content/uploads/2020/07/logo1-e1595189708614.png"

# Tautan Master Stream HLS Twitch langsung tanpa token IP runner
STREAM_URL = "https://usher.ttvnw.net/api/channel/hls/padang_tv.m3u8?client_id=kimne78kx3ncx6br8ac4x563ca126r&allow_source=true&allow_audio_only=true"

def main():
    ua_header = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"

    m3u_lines = [
        "<!--more-->",
        "<html>",
        "<head>",
        '<meta charset="utf-8">',
        '<meta http-equiv="X-UA-Compatible" content="IE=edge">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<script language=\"javascript\">",
        'window.location.replace("https://sulthanpamenan.github.io/pluto-playlist/");',
        "</script>",
        "</head></html>",
        "",
        "<================== PLAYLIST AUTOGENERATED BY SUTAN PAMENAN ==================>",
        "<================== BAGI YANG MENEMUKAN PLAYLIST INI MOHON UNTUK TIDAK DIJUAL ATAU DIBAGIKAN SEMBARANGAN DEMI KEUNTUNGAN PRIBADI ==================>",
        "",
        f'#EXTM3U url-tvg="{EPG_URL}"',
        f'#EXTINF:-1 tvg-id="PadangTV.id" tvg-name="Padang TV" tvg-logo="{LOGO_URL}" group-title="Local",Padang TV',
        f'#EXTVLCOPT:http-user-agent={ua_header}',
        f'#EXTVLCOPT:http-referrer=https://player.twitch.tv/',
        f"{STREAM_URL}"
    ]

    m3u_content = "\n".join(m3u_lines) + "\n"

    with open("playlist.m3u", "w", encoding="utf-8") as f:
        f.write(m3u_content)

    with open("playlist.txt", "w", encoding="utf-8") as f:
        f.write(STREAM_URL)

    print("[SUCCESS] Berkas `playlist.m3u` dan `playlist.txt` berhasil diperbarui.")

if __name__ == "__main__":
    main()
