import sys
import streamlink

EPG_URL = "https://sulthanpamenan.github.io/padang-tv-playlist/epg.xml"
LOGO_URL = "https://padangtv.id/wp-content/uploads/2020/07/logo1-e1595189708614.png"
TWITCH_CHANNEL_URL = "https://www.twitch.tv/padang_tv"

def get_stream_url():
    try:
        print("[*] Extracting stream URL via Streamlink...")
        streams = streamlink.streams(TWITCH_CHANNEL_URL)
        if "best" in streams:
            return streams["best"].url
        elif "worst" in streams:
            return streams["worst"].url
    except Exception as e:
        print(f"[!] Streamlink Exception: {e}")
    return None

def main():
    stream_url = get_stream_url()

    if not stream_url:
        print("[X] Failed to fetch stream URL.")
        sys.exit(1)

    ua_header = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36"

    m3u_lines = [
        "<!--more-->",
        "<html>",
        "<head>",
        '<meta charset="utf-8">',
        '<meta http-equiv="X-UA-Compatible" content="IE=edge">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<script language=\"javascript\">",
        'window.location.replace("https://sulthanpamenan.github.io/padang-tv-playlist/");',
        "</script>",
        "</head></html>",
        "",
        "<================== PLAYLIST AUTOGENERATED BY SUTAN PAMENAN ==================>",
        "<================== IF YOU FIND THIS PLAYLIST, PLEASE DO NOT SELL OR DISTRIBUTE IT FOR PERSONAL GAIN ==================>",
        "",
        f'#EXTM3U url-tvg="{EPG_URL}"',
        f'#EXTINF:-1 tvg-id="PadangTV.id" tvg-name="Padang TV" tvg-logo="{LOGO_URL}" group-title="Local",Padang TV',
        f'#KODIPROP:inputstreamaddon=inputstream.adaptive',
        f'#KODIPROP:inputstream.adaptive.manifest_type=hls',
        f'#KODIPROP:inputstream.adaptive.stream_headers=User-Agent={ua_header}&Referer=https://player.twitch.tv/',
        f"{stream_url}|User-Agent={ua_header}&Referer=https://player.twitch.tv/"
    ]

    m3u_content = "\n".join(m3u_lines) + "\n"

    with open("playlist.m3u", "w", encoding="utf-8") as f:
        f.write(m3u_content)

    with open("playlist.txt", "w", encoding="utf-8") as f:
        f.write(stream_url)

    print("[SUCCESS] Files updated successfully via Streamlink!")

if __name__ == "__main__":
    main()
